##################################################
### Install redis packages
- name: Install redis packages
  apt:
    pkg:
      - redis-server
    state: present

- name: Start Redis and enable the service in autostart
  service:
    name: redis-server
    state: started
    enabled: yes