# Variable setup.

- name: Ensure Redis is installed.
  apt:
    name: "{{ redis_package }}"
    state: present

# TODO fix redis error
- name: Ensure Redis is configured.
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: 0644
  notify: restart redis

- name: Ensure Redis is running and enabled on boot.
  service: "name={{ redis_daemon }} state=started enabled=no"
