### Install basic system packages
- name: Install basic packages
  apt: 
    pkg:
      - gnupg2
      - vim
      - git
      - curl
      - wget
      - zip
      - unzip
      - htop
      - iotop
      - postfix
      - debian-goodies
      - apt-transport-https
      - ca-certificates
      - imagemagick
      - python-openssl
    state: present

- set_fact: 
    nfs_enabled: "{{ nfs }}"
    
- name: Install NFS server
  apt:
    pkg:
      - nfs-kernel-server
      - portmap
    state: present
  when: nfs_enabled == true

### Convenience
- name: Configure inputrc / vimrc and motd for root
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
   - { src: inputrc, dest: /root/.inputrc }
   - { src: vimrc, dest: /root/.vimrc }
   - { src: inputrc, dest: /home/vagrant/.inputrc }
   - { src: vimrc, dest: /home/vagrant/.vimrc }
   - { src: motd, dest: /etc/motd }
   - { src: aliases, dest: /home/vagrant/.bash_profile }
  
- name: Set new welcome message  
  shell: |
    echo "PrintLastLog no" >> /etc/ssh/sshd_config
    rm -rf /etc/update-motd.d/*

- name: key pathfile create 
  file: 
    path: "{{ passfile }}"
    state: touch

