### Install basic system packages
- name: Install basic packages
  apt: 
    pkg:
      - postfix
      - apt-transport-https
      - ca-certificates
      - imagemagick
      - ufw
    state: present

- name: Edit some configs
  lineinfile:
    path: "{{ item.path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { path: '/etc/ssh/sshd_config', regexp: '^#PrintLastLog yes', line: PrintLastLog no }
    - { path: '/etc/ssh/sshd_config', regexp: '^#PermitRootLogin prohibit-password', line: "PermitRootLogin {{ permit_root_login }}" }
  notify:
    - restart sshd

- name: Create logs dir
  file:
    path: "{{ log_project_dir }}"
    state: directory
    recurse: yes
    owner: "{{ web_owner }}"
    group: "{{ web_group }}"
    mode: 750

# Firewall
- name: Allow everything and enable UFW
  ufw:
    state: enabled
    policy: '{{ ufw_policy }}'

- name: Set logging
  ufw:
    logging: 'off'

- name: limit connection to tcp
  ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Delete OpenSSH rule
  ufw:
    rule: allow
    name: OpenSSH
    delete: yes

- name: Allow all access to tcp port 80
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  loop: "{{ ufw_ports }}"

- name: Allow all access from RFC1918 networks to this host
  ufw:
    rule: allow
    src: '{{ item }}'
  loop:
    - '10.0.0.0/8'
    - '172.16.0.0/12'
    - '192.168.0.0/16'