##################################################
### Install basic system packages
- name: Install basic packages
  apt: 
    pkg:
      - vim
      - git
      - curl
      - wget
      - zip
      - unzip
      - htop
      - iotop
      - postfix
      - debian-goodies
      - apt-transport-https
      - ca-certificates
      - imagemagick
    state: present

- set_fact: 
    nfs_enabled: "{{ nfs }}"
    
- name: Install NFS server
  apt:
    pkg:
      - nfs-kernel-server
      - portmap
    state: present
  when: nfs_enabled == true

##################################################
### Convenience
- name: Configure inputrc / vimrc and motd for root
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
   - { src: inputrc, dest: /root/.inputrc }
   - { src: vimrc, dest: /root/.vimrc }
   - { src: inputrc, dest: /home/vagrant/.inputrc }
   - { src: vimrc, dest: /home/vagrant/.vimrc }
   - { src: motd, dest: /etc/motd }
  
- name: Set new welcome message  
  shell: |
    echo "PrintLastLog no" >> /etc/ssh/sshd_config
    rm -rf /etc/update-motd.d/*

##################################################
### Install and configute ufw firewall
- name: Set up firewall
  apt: 
    name: ufw
    state: present

- name: Allow Port 22
  ufw: 
    rule: allow 
    port: 22

- name: Start the firewall
  ufw: 
    state: enabled
