### Install basic system packages
- name: Install basic packages
  apt: 
    pkg:
      - gnupg2
      - vim
      - git
      - curl
      - wget
      - zip
      - unzip
      - htop
      - iotop
      - postfix
      - debian-goodies
      - apt-transport-https
      - ca-certificates
      - imagemagick
    state: present
    
- name: Install NFS server
  apt:
    pkg:
      - nfs-kernel-server
      - nfs-common
    state: present
  when: nfs == true

### Convenience
- name: Configure inputrc / vimrc and motd for root
  become: yes
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
   - { src: inputrc, dest: /root/.inputrc }
   - { src: vimrc, dest: /root/.vimrc }
   - { src: inputrc, dest: /home/vagrant/.inputrc }
   - { src: vimrc, dest: /home/vagrant/.vimrc }
   - { src: motd, dest: /etc/motd }
   - { src: bashrc, dest: /home/vagrant/.bashrc }
   - { src: aliases, dest: /home/vagrant/.bash_aliases }
  force: yes
  
- name: Set new welcome message  
  shell: |
    echo "PrintLastLog no" >> /etc/ssh/sshd_config
    rm -rf /etc/update-motd.d/*