### Install and configure webserver
- name: Add apt key for Debian
  apt_key: 
    url: "https://nginx.org/keys/nginx_signing.key"
    state: present

- name: Add repository for Debian
  apt_repository: 
    repo: "{{ item }} http://nginx.org/packages/{{ nginx_release }}/debian/ {{ ansible_distribution_release }} nginx"
    state: present
    update_cache: yes
  loop:
    - deb
    - deb-src

- name: Install webserver
  apt:
    name: nginx
    state: latest

- name: Create folders
  file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    state: directory
  loop:
    - { path: "/etc/nginx/sites-available", mode: 755, user: root, group: root }
    - { path: "/etc/nginx/sites-enabled", mode: 755, user: root, group: root }
    - { path: "/var/lib/nginx", mode: 777, user: vagrant, group: root }
    - { path: "/var/lib/nginx/tmp", mode: 777, user: vagrant, group: root }
    - { path: "/var/run/{{ projectname }}", mode: 755, user: vagrant, group: root }
    - { path: "{{ nginx_log_dir }}", mode: 755, user: vagrant, group: vagrant }

- name: Build all config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: nginx.conf, dest: /etc/nginx/nginx.conf }
    - { src: proxy.conf, dest: "/etc/nginx/{{ projectname }}_proxy" }
    - { src: gzip.conf, dest: /etc/nginx/conf.d/gzip }
    - { src: brotli.conf, dest: /etc/nginx/conf.d/brotli }
    # auto importing configs
    - { src: settings.conf, dest: /etc/nginx/conf.d/settings.conf }
    - { src: backends.conf, dest: /etc/nginx/conf.d/backends.conf }

- name: Start Nginx and enable the service in autostart
  service:
    name: nginx
    state: started
    enabled: yes
