 - hosts: all
   vars_files:
    - vars/globals.yml
    - vars/mysql.yml
    - vars/mailer.yml
   roles:
    - { role: basics }
    - { role: updates }
    - { role: ssl }
    - { role: nginx }
    - { role: php }
    # - { role: mysql }
    - { role: redis }
    - { role: nodejs }
    - { role: tests, when: testing_mode == 1 }
    - { role: symfony, when: projectname != 0 }
    - { role: clean }
   post_tasks:
    - service: 
        name: nginx
        state: restarted
    - service:
        name: "php{{ php_version }}-fpm"
        state: restarted
