 - hosts: default
   vars_files:
    - vars/globals.yml
   roles:
    - { role: basics }
    - { role: ssl,  when: ssl == true }
    - { role: nginx }
    - { role: php }
    - { role: mysql }
    - { role: redis, when: skip_redis != true    }
    - { role: nodejs }
    - { role: tests, when: testing_mode == 1 }
    - { role: symfony, when: projectname != 0 }
    - { role: nfs, when: nfs == true }
    - { role: clean }
   post_tasks:
    - service: 
        name: nginx
        state: restarted
    - service:
        name: "php{{ php_version }}-fpm"
        state: restarted
    - service:
        name: mysql
        state: restarted
