- name: Cron dumping db
  block:
  - name: log file
    file:
        path: "{{ cron_log_dir }}"
        state: directory

  - name: Dump database
    become: yes
    cron:
        name: "dump database"
        user: "{{ web_owner }}"
        minute: "0"
        hour: "2"
        job: "{{ db_update }} >> {{ db_update_cron_log_file }}"
