---
- set_fact:
    app_secret: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters') }}"

- name: Check if composer project is initialized
  stat:
    path: "{{ dir }}"
  register: stat_project

#- name: Stat project
#  debug:
#     msg: "{{ stat_project }}"

- name: Init work folder
  stat:
    path: "{{ data_dir }}"
  register: stat_project_data

- name: Unmount directory
  mount:
    path: "{{ web_dir }}"
    state: unmounted
  when: stat_project.stat.exists == true and nfs == true

- name: Prepare fresh directory
  become: yes
  file:
    path: "{{ dir }}"
    state: absent
  when: stat_project.stat.exists == false

- name: Correct permissions
  file:
    dest: "{{ data_dir }}"
    owner: "{{ web_owner }}"
    group: "{{ web_group }}"
    state: directory
    mode: "{{ web_chmod }}"
    recurse: yes

- name: Clone the code repository to the docroot.
  git:
    repo: "{{ src_repo }}"
    dest: "{{ dir }}"
    version: "{{ src_branch }}"
  become_user: "{{ web_owner }}"
  when: stat_project.stat.exists == false

- name: parameters
  template:
    src: parameters_dev.yaml
    dest: "{{ web_dir }}/config/parameters.yaml"

- name: PhpUnit
  template:
    src: phpunit.xml
    dest: "{{ web_dir }}/phpunit.xml"
    owner: "{{ web_owner }}"

# Symfony 5
- name: Init symfony5 project
  composer:
    command: install
    working_dir: "{{ web_dir }}"
    no_dev: "{%if app_env != 'dev'%}yes{%else%}no{%endif%}"
  environment:
    APP_ENV: "{{ app_env }}"
  become_user: vagrant
  register: new_symfony_project
  ignore_errors: yes
  when: stat_project.stat.exists == false

- name: clean
  file:
    path: "{{ item.path }}"
    state: absent
  loop:
    - { path: .env }
    - { path: .env.test }
    - { path: "{{ dir }}/.git" }

- name: Dump schema
  command: "{{ sf_console }} doctrine:schema:update -f --no-interaction"
  ignore_errors: "{%if app_env == 'dev' %}yes{%else%}no{%endif%}"

- name: Copy new virtual hosts file.
  template:
    src: default.conf
    dest: "/etc/nginx/sites-available/{{ projectname }}"
 
- name: Enable new virtual hosts file.
  file:
    src: "/etc/nginx/sites-available/{{ projectname }}"
    dest: "/etc/nginx/sites-enabled/{{ projectname }}"
    state: link
  notify:
   - restart nginx

- name: Include cron config for project
  include_tasks: cron.yml
  when: app_env != 'prod'
