### Configure symfony project
- name: Start project creation
  debug: 
    msg: "{{ projectname }}"

- set_fact: 
    symfony_major_version: "{{ symfony_version | int }}"

- name: Check if project already exists
  stat:
    path: "{{ web_path }}"
  register: stat_project

- name: Create project directory
  file:
    path: "{{ web_path }}"
    state: directory
  become_user: vagrant
  when: stat_project.stat.exists == false

# Symfony 5
- name: Create symfony5 project
  composer:
    command: install
    arguments: --no-interaction
    args:
      chdir: "{{ web_path }}"
    working_dir: "{{ web_path }}"
    prefer_dist: yes
  environment:
    APP_ENV: "{{ app_env }}"
  become_user: vagrant
  register: new_symfony_project
  when: stat_project.stat.exists == false and symfony_major_version == "5"

# - name:  Install composer
#   command: composer install --no-interaction
#   args:
#     chdir: "{{ web_path }}"
#   become_user: vagrant
#   when: new_symfony_project.changed and symfony_major_version == "5"

# Clean solution, but with problems on Linux hosts
# - name: Install composer
#   composer:
#     command: install
#     working_dir: "{{ web_path }}"
#   become_user: vagrant
#   when: new_symfony_project.changed

##################################################
### Configure nginx
# - name: Copy new virtual hosts file.
#   template:
#     src: nginx_project_vhost_symfony{{ symfony_major_version }}.skel
#     dest: /etc/nginx/sites-available/{{ projectname }}
#     force: no

# - name: Enable new virtual hosts file.
#   file:
#     src: /etc/nginx/sites-available/{{ projectname }}
#     dest: /etc/nginx/sites-enabled/{{ projectname }}
#     state: link
#   notify:
#    - restart nginx