---
- set_fact:
    app_secret: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters') }}"

- name: Check if composer project is initialized
  stat:
    path: "{{ dir }}"
  register: stat_project

# - name: Stat project
#   debug: 
#     msg: "{{ stat_project }}"

- name: Create project directory
  become: yes
  file:
    path: "/data"
    state: directory
    owner: vagrant
    group: vagrant
  when: stat_project.stat.exists == false

- name: Prepare fresh directory
  become: yes
  file:
    path: "{{ dir }}"
    state: absent
  when: stat_project.stat.exists == true

- name: Clone the code repository to the docroot.
  git:
    repo: "{{ src_repo }}"
    dest: "{{ dir }}"
  become_user: vagrant

- name: remove git repo
  file:
    path: "{{ dir }}/.git"
    state: absent

# Symfony 5
- name: Create symfony5 project
  composer:
    command: install
    working_dir: "{{ web_dir }}"
    prefer_dist: yes
  environment:
    APP_ENV: "{{ app_env }}"
  become_user: vagrant
  register: new_symfony_project
  ignore_errors: yes

- name: Copy new virtual hosts file.
  template:
    src: default.conf
    dest: /etc/nginx/sites-available/{{ projectname }}
 
- name: Enable new virtual hosts file.
  file:
    src: /etc/nginx/sites-available/{{ projectname }}
    dest: /etc/nginx/sites-enabled/{{ projectname }}
    state: link
  notify:
   - restart nginx