---
nfs_server_daemon: nfs-kernel-server
nfs_version: 3
nfs_private_ip: "{%if nfs_version == 4 %}{{ private_ip }}/24{% else %}{{ private_ip }}{% endif %}"

nfs_exports: 
  - { path: "{{ web_dir }}", export: "{{ nfs_private_ip }}(rw,nohide,all_squash,insecure,no_subtree_check,sync)" }

nfs_rpcbind_state: started
nfs_rpcbind_enabled: true

# depth conf 
# /etc/nfs-commons  (choices yes / no / "")
NEED_STATD: "no"
STATDOPTS: ""
NEED_IDMAP: "yes"
NEED_GSSD: ""

# /etc/nfs-kernel-server  (see nfs-kernel-server docs)
# Number of servers to start up
RPCNFSDCOUNT: 
# Runtime priority of server (see nice(1))
RPCNFSDPRIORITY: 0

# Options for rpc.mountd.
# If you have a port-based firewall, you might want to set up
# a fixed port here using the --port option. For more information,
# see rpc.mountd(8) or http://wiki.debian.org/SecuringNFS
# To disable NFSv4 on the server, specify '--no-nfs-version 4' here
RPCMOUNTDOPTS: "--manage-gids"

#Do you want to start the svcgssd daemon? It is only required for Kerberos
#exports. Valid alternatives are "yes" and "no"; the default is "no".
NEED_SVCGSSD: "no"

# Options for rpc.svcgssd.
RPCSVCGSSDOPTS: ""