- name: Ensure we deleted default nginx welcome page
  file: 
    path: "/etc/nginx/sites-enabled/default"
    state: absent
    force: yes
  become: yes
  notify:
   - restart nginx

- name: Delete nginx default conf
  file: 
    path: "/etc/nginx/conf.d/default.conf"
    state: absent
    force: yes
  become: yes
  notify:
   - restart nginx

- name: Remove python db manager
  apt:
    pkg:
      - python-pymysql
    update_cache: yes
    state: absent

- name: clean olders php installs
  become: yes
  shell: |
    "apt purge php{{ item }} libapache2-mod-php{{ item }} 
    rm -rf /etc/php/php{{ item }}"
  loop: "{{ prune_php_versions }}"

- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: full
    update_cache: yes
    cache_valid_time: 86400
 
- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
    purge: yes
    force: yes
    update_cache: true
  become: yes
  tags:
    - system

- name: Build script to clean everything
  template:
    src: cleaner.j2
    dest: /tmp/cleaner.sh