- name: Remove python openssl
  apt: 
    pkg:
      - python-openssl
    state: absent

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: full
    update_cache: yes
    cache_valid_time: 86400
 
# sudo apt-get autoremove
- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
    purge: yes
    force: yes
  tags:
    - system