---
- name: Ensure NFS utilities are installed.
  apt:
    name:
      - nfs-common
      - nfs-kernel-server
    state: present

- name: Copy paramaters files.
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: exports.j2, dest: /etc/exports }
    #- { src: imapd.j2, dest: /etc/idmapd.conf }
    #- { src: nfs-kernel-server.j2, dest: /etc/exports }
    #- { src: nfs-commons.j2, dest: /etc/commons }
  notify: reload nfs

- name: Ensure nfs is running.
  service: 
    name: "{{ nfs_server_daemon }}"
    state: started 
    enabled: yes
  when: nfs_exports|length

- name: Ensure rpcbind is running
  service: 
    name: rpcbind
    state: "{{ nfs_rpcbind_state }}"
    enabled: "{{ nfs_rpcbind_enabled }}"