---
- name: Ensure NFS utilities are installed.
  apt:
    name:
      - nfs-common
      - nfs-kernel-server
      - bindfs
    state: present

#- name: Copy paramaters files.
  #lineinfile:
    #path: /etc/fstab
    #line: "{{ web_dir }} {{ web_dir }} bind bind"
    #create: yes
  #notify: reload nfs

#- name: fix nfs on mac os
#  shell: |
#    "sudo bindfs --map=501/{{ web_owner }}:@dialout/@{{ web_group }} {{ web_dir }} {{ web_dir }}"
#  notify: reload nfs

- name: Ensure nfs is running.
  service: 
    name: "{{ nfs_server_daemon }}"
    state: started 
    enabled: yes
  when: nfs_exports|length

- name: Ensure rpcbind is running
  service: 
    name: rpcbind
    state: "{{ nfs_rpcbind_state }}"
    enabled: "{{ nfs_rpcbind_enabled }}"