---
- name: Ensure NFS utilities are installed.
  apt:
    name:
      - nfs-common
      - nfs-kernel-server
    state: present

- name: Ensure nfs is running.
  service: 
    name: "{{ nfs_server_daemon }}"
    state: started 
    enabled: yes
  when: nfs_exports|length and vagrant_nfs_used == false

- name: Ensure rpcbind is running
  service: 
    name: rpcbind
    state: "{{ nfs_rpcbind_state }}"
    enabled: "{{ nfs_rpcbind_enabled }}"