### Variable depending on env
- include_vars: "../defaults/php_ini_{{ app_env }}.yml"

- name: Check installed PHP version
  shell: 'dpkg --list | grep php | grep "^ii" | wc -l'
  register: php_installed

#php_required_installed
- name: Check if required PHP version is installed
  shell: 'dpkg --list | grep php{{ php_version }} | grep "^ii" | wc -l'
  register: php_required_installed

- name: Remove different PHP version if installed
  apt:
    name: php*
    state: absent
    purge: yes
    autoremove: yes
  when: php_installed.stdout != "0"

### Install and configure PHP
- name: Add apt key for Debian
  apt_key:
    url: "{{ php_repo_key }}"
    state: present

- name: Add repository for Debian
  apt_repository: 
    repo: "deb {{ php_repo }} {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Install PHP Packages
  apt:
    state: present
    pkg:
    - "php{{ php_version }}-{{item}}"
  loop: "{{ php_modules }}"
  notify:
   - restart php-fpm
   - restart nginx
  when: update_php == true

- name: Copy PHP-FPM config
  template:
    force: "{{ update_php }}"
    src: www.conf
    dest: /etc/php/{{ php_version }}/fpm/pool.d/www.conf

- name: Configure timezone
  lineinfile:
    dest: /etc/php/{{ php_version }}/fpm/php.ini
    regexp: '^;date.timezone'
    line: 'date.timezone = "Europe/Paris'
    backrefs: yes
  notify:
   - restart php-fpm

- name: Copy xdebug ini into main extension config folder.
  template:
    src: xdebug.ini.j2
    dest: "{{ php_xdebug.module_path }}/20-xdebug.ini"
    owner: root
    group: root
    mode: 0644
  when: php_xdebug.cli_disable != true
  notify:
    - restart php-fpm
    - restart nginx

- name: Disable xdebug for PHP CLI.
  file:
    path: "{{ php_xdebug.module_path }}/20-xdebug.ini"
    state: absent
  when: php_xdebug.cli_disable == true
  notify:
    - restart php-fpm
    - restart nginx

- name: Start PHP-FPM and enable the service in autostart
  service:
    name: php{{ php_version }}-fpm
    state: started
    enabled: yes

### Install Composer
- name: Download Composer
  get_url:
    url: "{{ composer_url }}"
    dest: "{{ composer_tmp }}"
    mode: 0777

- name: Install Composer
  shell: "cat {{ composer_tmp }} | php -- --install-dir={{ composer_path }}"

- name: Rename Composer
  shell: mv -f {{ composer_path }}/composer.phar {{ composer_path }}/composer

- name: php.ini configuration
  template:
    force: "{{ update_php }}"
    src: "php.ini.j2"
    dest: "{{ php_config_file }}" 
    owner: root
    group: root
    mode: 0644
  notify: restart php-fpm