---

# ssl (used in nginx conf)
ssl_nginx_conf_path: "/etc/nginx/ssl"
ssl_nginx_main_conf : "{{ ssl_nginx_conf_path }}/ssl_main.conf"
ssl_nginx_server_conf : "{{ ssl_nginx_conf_path }}/ssl_{{ projectname }}.conf"
ssl_pass: 'Azerty69'

ssl_certs_country: "FR"
ssl_certs_locality: "Paris"
ssl_certs_organization: "g4-dev"
ssl_certs_state: "Paris"
ssl_certs_common_name: "{{ servername }}"
ssl_certs_san_name: "{{ ssl_certs_common_name }}"
ssl_certs_email: "loic.roux.404@gmail.com"
ssl_certs_days: "365"
ssl_certs_fields: "/C={{ ssl_certs_country }}/ST={{ ssl_certs_state }}/L={{ ssl_certs_locality }}/O={{ ssl_certs_organization }}/CN={{ ssl_certs_common_name }}"

ssl_certs_path: "/etc/ssl/{{ ssl_certs_common_name }}"
ssl_certs_conf_path: "{{ ssl_certs_path }}/{{ ssl_certs_common_name }}"
ssl_certs_path_owner: "vagrant"
ssl_certs_path_group: "vagrant"
ssl_certs_privkey_path: "{{ ssl_certs_path }}/{{ ssl_certs_common_name }}.key"
ssl_certs_cert_path: "{{ ssl_certs_path }}/{{ ssl_certs_common_name }}.pem"
ssl_certs_csr_path: "{{ ssl_certs_path }}/{{ ssl_certs_common_name }}.csr"
ssl_certs_combined_path: "{{ ssl_certs_path }}/{{ ssl_certs_common_name }}.combined.pem"
ssl_certs_dhparam_path: "{{ ssl_certs_path }}/dhparam.pem"
ssl_certs_pkcs12_path: "{{ ssl_certs_path }}/pkcs12.pfx"
ssl_certs_crt_path: "{{ ssl_certs_path }}/{{ ssl_certs_common_name }}.crt"
ssl_certs_mode: "0600"
ssl_certs_force_replace: yes

ssl_certs_local_privkey_path: "{{ inventory_dir|default(playbook_dir) }}/files/ssl/{{ ssl_certs_common_name}}.key"
ssl_certs_local_cert_path: "{{ inventory_dir|default(playbook_dir) }}/files/ssl/{{ ssl_certs_common_name }}.pem"
ssl_certs_local_privkey_data: ""
ssl_certs_local_cert_data: ""

ssl_certs_generate_self_signed: true
ssl_certs_key_size: "2048"
ssl_certs_generate_dh_param: true
ssl_certs_dhparam_size: "2048"