php_version: 7.4
php_repo_key: https://packages.sury.org/php/apt.gpg
php_repo: https://packages.sury.org/php/
composer_url: https://getcomposer.org/installer
composer_tmp: /tmp/composer_installer
composer_path: /usr/local/bin/
