php_config_dir: "/etc/php/{{ php_version }}/fpm"
php_config_file: "{{ php_config_dir }}/php.ini"
fpm_config_file: "{{ php_config_dir }}/php-fpm.conf"

# [PHP]
upload_max_filesize: 20M
post_max_size: 32M 
memory_limit: 256M 
max_execution_time: '600' 
max_input_vars: '3000' 
max_input_time: '1000'

realpath_cache_size: '4096K'
realpath_cache_ttl: '600'

# [opcache]
opcache:
  enable: '1'
  preload: ''
  memory_consumption: '256'
  max_accelerated_files: '20000'
  validate_timestamps: '1'
  interned_strings_buffer: '10MB'
  fast_shutdown: '1'
  force_restart_timeout: '60'
  error_log: '0'

# [XDebug]
php_xdebug: 
  default_enable: 1
  coverage_enable: 1
  module_path: /etc/php/{{ php_version }}/fpm/conf.d
  remote_enable: "false"
  remote_connect_back: "false"
  remote_host: localhost
  remote_port: "9000"
  remote_log: "{{ log_project_dir }}/xdebug.log"
  remote_autostart: "false"
  max_nesting_level: 256
  cli_disable: true