permit_root_login: "yes"
ufw_policy: "allow"
ufw_ports:
    - '80'
    - '81'
    - '82'
    - '3306'
    - '5432'
    - '22'

# SMB part
smb_enabled: "{% if smb is defined and smb == true %}yes{% else %}no{% endif %}"
smb_package: cifs-utils